### ISSUE TITLE
A-10C ii Tank Killer support

### ISSUE THREAD

**Issue by mrdimsum99** [charlestytler/streamdeck-dcs-interface#17]
Hi there,

First of all let me say thank you for this wonderful plugin. It works beautifully with my Elgato Streamdeck XL and the A-10C.

Now that the A-10C Tank Killer is out, will this be made compatible with it? Does it solely depend on the DCS Exports Scripts?

Thank you!

**Comment by charlestytler** [comment]
Hi, I've tried to keep this plugin decoupled from the export scripts since other maintained projects already exist and I wanted this to be stable across ED patches and modules. That said, a user [on the ED forums reported the following](https://forums.eagle.ru/showthread.php?t=269642&page=28):

> SmilingBandit:
> I copied the A-10C.lua in the ExportsModule folder to A-10C_2.lua and it seems to be working so far. They didn't change the data fields for any of the input or outputs.
> 
> I didn't have anything mapped to the LASTE panel so I don't know how that will behave, but so far so good.

**Comment by mrdimsum99** [comment]
> Hi, I've tried to keep this plugin decoupled from the export scripts since other maintained projects already exist and I wanted this to be stable across ED patches and modules. That said, a user [on the ED forums reported the following](https://forums.eagle.ru/showthread.php?t=269642&page=28):
> 
> > SmilingBandit:
> > I copied the A-10C.lua in the ExportsModule folder to A-10C_2.lua and it seems to be working so far. They didn't change the data fields for any of the input or outputs.
> > I didn't have anything mapped to the LASTE panel so I don't know how that will behave, but so far so good.

Thanks for the quick reply! I also see your post where you state that the ID lookup table doensn't yet work for the A-10C_2 but that the IDs are the same so far.

Together with the other user's solution I should manage to get it working for me.

**Comment by dmjohnsnx2** [comment]
@mrdimsum99  can I get a copy of your export script?  And where exactly did you put the file? I followed the directions from the YouTube video, but I must have missed something along the way but I can't find the error. I've got a stream deck hooked up, I'm getting the export message from the stream deck, but not from this link.  "com.ctytler.dcs#.log
So there's something broken somewhere  but I'm not sure which script file it goes into.

**Comment by mrdimsum99** [comment]
@dmjohnsnx2 I created a repository for you on my GitHub profile.

I put the files in ..\Saved Games\DCS.openbeta\Scripts\DCS-ExportScript

**Comment by dmjohnsnx2** [comment]
I'm still not getting it to run correctly and I'm not sure what I'm doing wrong. It may end up being something really simple and stupid.
I've tried to put it in both export setting files with no luck in either of them.
This one ...\Saved Games\DCS\Scripts\DCS-ExportScripts-1.2.1-2\DCS-ExportScript
And this one...\Saved Games\DCS\Scripts\DCS-ExportScripts-1.2.1-2

**Comment by mrdimsum99** [comment]
@dmjohnsnx2 Afaik the last one should be the correct way.

Maybe check the config.lua and comms settings in Streamdeck. Make sure both application and script are able to talk over the same port?

**Comment by dmjohnsnx2** [comment]
The IP Address, Listener Port and Send Port are all correct but still "no DCS module detected" message is displayed.
When I run this "%appdata%\Elgato\StreamDeck\logs" I get logs, but when I run this "com.ctytler.dcs#.log    Windows can't find it.  Does this make any sense? I'm not a coder so I don't know.

**Comment by charlestytler** [comment]
Hi @dmjohnsnx2 responding in this thread as well. The "no DCS module detected" is likely due to the ExportScript not configured correctly.

Couple things to check:
1. Check that you have a file `Saved Games\DCS\Scripts\Export.lua`, if it doesn't exist you'll need to create it.

2. Within that Export.lua text file you'll want the line: `dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]])`
This is basically code telling the game to include the commands found in the file `Scripts\DCS-ExportScript\ExportScript.lua` (the path is specified as if you were to start in the `Saved Games\DCS` folder)

3. Make sure you've copied over the DCS-ExportScript contents such that the file `Saved Games\DCS\Scripts\DCS-ExportScript\ExportScript.lua` exists -- with that exact folder path.

I'm thinking your problem is within Scripts you have the whole `DCS-ExportScripts-1.2.1-2` copied into the Scripts folder such that it looks like: `Saved Games\DCS\Scripts\DCS-ExportScripts-1.2.1-2\Scripts\DCS-ExportScript\ExportScript.lua`

If so, you need to move that content up higher to remove the `DCS-ExportScripts-1.2.1-2\Scripts` subfolders from that path. Hopefully you kept up with me writing the word "Script" about 50 times there.

**Comment by dmjohnsnx2** [comment]
I ordered a Stream Deck XL but it got caught up in the TX weather so it won't be in til Wednesday and I returned the smaller one. I'll get back to you as soon as I can get back to work with a deck, it sounds like it should be really easy. 
I think the best thing for me to do is strip the file down to bare bones and start over with a fresh, clean _scripts_  folder.

**Comment by dmjohnsnx2** [comment]
I'm hooked up, I have the file with this exact folder path  _saved games\DCS\Scripts\DCS-ExportScript\ExportScript.lua_

I've done steps 1-3 as shown above, I went through your video on YouTube again for the installation of the Stream Deck
I used the Export Script  mrdimsum99 put up for me, but it still doesn't want to link.

And this still doesn't bring up any log files "com.ctytler.dcs#.log but I can get log files from stream deck.

**Comment by charlestytler** [comment]
So to check if the Export script is working, start a DCS mission then see if it's creating a log file and if there are any errors in:
`Saved Games\DCS\Logs\Export.log`
Mine shows, for example:
```
ExportScript Version: 1.2.1
00:04:08:828 : Create UDPSender
00:04:08:828 : Create UDPListner
00:04:08:829 : File Path: C:\Users\ct\Saved Games\DCS\Scripts\DCS-ExportScript\ExportsModules\AJS37.lua
00:04:08:829 : File 'C:\Users\ct\Saved Games\DCS\Scripts\DCS-ExportScript\ExportsModules\AJS37.lua' loaded
00:04:08:829 : Version:
00:04:08:829 : Config: 1.2.1
00:04:08:829 : Maps: 1.2.1
00:04:08:829 : Tools: 1.2.1
00:04:08:829 : AJS37: 1.2.1
00:04:08:829 : genericRadio: 1.2.1
00:04:08:829 : ExportScript: 1.2.1
00:04:08:829 : Detected Map: CaucasusBase
00:04:21:698 : reset dcs ikarus
00:12:14:934 : ====== Logfile close ======
```

If that is working, then check the Streamdeck plugin, create a button from the DCS Interface and in it's settings menu click "DCS Comms" and click the "Refresh" button. If you click Refresh while the game is running, it should print out a table of data it's receiving which would mean it's all working.

**Comment by dmjohnsnx2** [comment]
I've got it working, Finally! Thanks for your patience. Now comes the long task of setting up my profile.

**Comment by charlestytler** [comment]
Excellent! Glad it worked out!

**Comment by mrdimsum99** [comment]
@dmjohnsnx2 Glad to hear you got it working!

I'm happy to share my profile with you; it has F/A-18 and A-10C (which also works with A-10C ii): 
[Dimsum Streamdeck profile.zip](https://github.com/charlestytler/streamdeck-dcs-interface/files/6056492/Dimsum.Streamdeck.profile.zip)

Maybe it saves you some work

**Comment by dmjohnsnx2** [comment]
Thanks, I looked at your profile, its great. I'll definitely work it into my profile once I can get everything working both directions. My stream deck is just mirroring what position switches are in in the plane, the stream deck will not control the plane. Neither the profile you set up, nor the profile Charles set up will work on my system.I can bind keys and make controls work that way so I know that the stream deck will work. I'm not a programmer or code writer so I'm lost when it comes to those workings.
-------- Original message --------From: Deon Kidjo <notifications@github.com> Date: 2/28/21  1:24 AM  (GMT-08:00) To: charlestytler/streamdeck-dcs-interface <streamdeck-dcs-interface@noreply.github.com> Cc: Dave Johnson <dmjohnsnx2@aol.com>, Mention <mention@noreply.github.com> Subject: Re: [charlestytler/streamdeck-dcs-interface] A-10C ii Tank Killer support (#17) 
@dmjohnsnx2 Glad to hear you got it working!
I'm happy to share my profile with you; it has F/A-18 and A-10C (which also works with A-10C ii):
Dimsum Streamdeck profile.zip
Maybe it saves you some work
