### ISSUE TITLE
DCS World Export Scripts for M2000C

### ISSUE THREAD

**Issue by D4Gi** [charlestytler/streamdeck-dcs-interface#18]
Hallo

Really good work on the Stream Deck interface!

I know you are not the developer of the "DCS World Export Scripts", but I saw in one of your tutorials that you found some things that could/had to be changed to get the export to work correctly.
("Increment (pt 2 - switches) - DCS Interface for Streamdeck" on YouTube)

I had some hard times trying to export the PCA from the Mirage 2000C this weekend.
Eg., the IDs 2010 to 2014 are all just "0".

Have you looked into this by any chance?

**Comment by charlestytler** [comment]
There is now a new repository for module update/maintenance questions, can be found here:
https://github.com/asherao/DCS-ExportScripts
