### ISSUE TITLE
A tool for regeneration of the cached_commands.js

### ISSUE THREAD

**Issue by rstoki** [charlestytler/streamdeck-dcs-interface#19]
Hello,

I wanted to ask, if you have and/or plan to have a tool, that would be capable to regenerate the content of 
`\Sources\com.ctytler.dcs.sdPlugin\propertyinspector\json\cached_commands.js`? 

In the current situation, the 'library' of commands (in StreamDeck-DCS-interface) includes "only" 11 modules. On the other hand, there are approx. 40 modules currently supported by DCS-ExportScript (e.g.: https://github.com/rstoki/DCS-ExportScripts/tree/master/Scripts/DCS-ExportScript/ExportsModules). 

It would be great if the "ID Lookup Library" could be regenerated to match present state.  

So before I start to create such tool by myself (in order to regenerate it and send you a pull-request), I am asking if there is (by any chance) already usable tool for the regeneration?

**Comment by charlestytler** [comment]
Hi, the ID Lookup [queries the modules](https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Sources/DcsInterface/DcsIdLookup.h#L15) installed in your DCS World install directory and only shows those, which may be why you're only seeing 11. You may be able to mock this by putting an empty folder with the desired module name in `DCS World/mods/aircraft/`.

The lookup data is then pulled from the installed module's configs with a [lua script](https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Sources/com.ctytler.dcs.sdPlugin/extract_clickabledata.lua), and the cached data is only there[ in case that fails](https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Sources/com.ctytler.dcs.sdPlugin/propertyinspector/js/id_lookup_window_functions.js#L183).

Note that Flaming Cliffs aircraft have their own drop down, and it only pulls in clickable-data; so if an aircraft doesn't have a clickable cockpit it won't be able to pull in any commands. I also created a small repo with the lua console to run that script standalone if that's of any interest: https://github.com/charlestytler/dcs-clickabledata-extract

Sorry for the confusing folder structure, it's based off of the Streamdeck C++ plugin template example and I thought it made sense to keep it aligned with that for anyone viewing it alongside Streamdeck SDK examples.

Let me know if that answers your question, or if there is something that's missing. Also thanks for the interest and willingness to add on capability.
