### ISSUE TITLE
Applying a factor to exported values

### ISSUE THREAD

**Issue by Mr-7** [charlestytler/streamdeck-dcs-interface#22]
Trying to configure some buttons to show the Mach number and distance to target. But the last Mach number digit and the distance both get output as 4 decimal place numbers where every number is different so it isn't practical to list all of them in the text map box. Is there a way to just multiply the exported number by a set value or move the decimal place?

**Comment by charlestytler** [comment]
This is a duplicate of requested enhancement #16 

Note: you can also edit outputs or do unit conversions in the module's `.lua` export script in the meantime.

**Comment by Mr-7** [comment]
Yeah I ended up doing this after following your tutorial. I’ve managed to export the Ka50 PVI displays and the viggens computer displays. Great stuff!
