### ISSUE TITLE
Plugin problem with double DCS installation, Stable work and Open Beta not

### ISSUE THREAD

**Issue by Valium64** [charlestytler/streamdeck-dcs-interface#23]
Hi, I have two DCS installations, the Stable and the Open Beta, both of which install on an additional disk with the folders in both savegames in the user folder.
I performed exactly the same procedure for both release by installing the DCS-Bios v0.10.0 on the PC, modifying in both installation the "script \ Export.lua" with the command for enabling BIOS and "script \ bin \ Config.lua" with the port modifyed to 1725 in the same way, copied to both installation savedgame in "script" the "DCS-ExportScript" folder of version 1.2.1, if launching the two versions alternately if I open DCS-BIOS Hub from web browser in DCS Connection I see both installations green with all three ticks for each activated, runnung the two release alternatively with a mission started in Lua Console i see the DCS Connection green as in the Dashboard I see green both Virtual Cockpit and Lua Console, but from the Stable installation if I test the connection from the StramDeck with the DCS Interface v1.0.3 plug-in installed and port changed to 1725 everything works correctly and I see the commands sent and the values ​​of been read, if instead I launch the Open Beta it does not connect or write anything.
I also tried renaming the Open Beta installation and re-launching an installation in the same path then remove the new installation and restore the original but nothing changes.
Some idea?

P.S.
Stable version was the first installed and work fine, then Open Beta was installed later.

**Comment by charlestytler** [comment]
First, from your description DCS-ExportScript is set to 1725, but you're not setting anything to 1725 in DCS-Bios, correct?

It sounds like there may be something erroring in the .lua scripts potentially. There's a couple things I would suggest checking/trying:

- Look at `Saved Games\DCS\Logs\dcs.log` for any messages that may indicate an error within Lua scripts
- Look at `Saved Games\DCS\Logs\Export.log` for any error messages that DCS-ExportScript may output.
(Note you can also set `ExportScript.Config.Debug` to `true` in `Saved Games\DCS\Scripts\DCS-ExportScript` for more detailed logging)
- Try commenting out (with `--`) all but one dofile command at a time within `Scripts\Export.lua` to see if you can narrow down which scripts have issues; often if one fails, the following scripts will also fail.

**Comment by Valium64** [comment]
Hi and thanks for your kind reply.

So, as far as port 1725 is concerned, I changed it both on the StreamDeck and in DCS-ExportScript in the CONFIG.LUA file, I tried both to change that directly for Ikarus and to add a new dedicated command set for the StreamDeck to exactly the same way for both Stable and OpenBeta, but for the latter it doesn't work in any way.

Below are the changes made to the two files as indicated in the plugin installation document.

CONFIG.LUA in script \ DCS-ExportSript

> - Ikarus and D.A.C. Export Script
> -
> - Config File
> -
> - Copyright by Michael aka McMicha 2014
> - Contact dcs2arcaze.micha@farbpigmente.org
> 
> ExportScript.Config = {}
> ExportScript.Version.Config = "1.2.1"
> 
> - Ikarus at Glass Cockpit Software
> ExportScript.Config.IkarusExport = true - false for not use
> ExportScript.Config.IkarusHost = "127.0.0.1" - IP for Ikarus
> ExportScript.Config.IkarusPort = 1625 - Port Ikarus (1625)
> ExportScript.Config.IkarusSeparator = ":"
> 
>         - V64 Note: Added for Streamdeck DCS Interface (IkarusExport must also be true)
>         ExportScript.Config.StreamdeckExport = true - false for not use
>         ExportScript.Config.StreamdeckHost = "127.0.0.1" - IP for DCS Interface
>         ExportScript.Config.StreamdeckPort = 1725 - Port DCS Interface (1725)
>         - V64 Note: End of modification
> 
> - D.A.C. (DCS Arcaze Connector)
> ExportScript.Config.DACExport = false - true for use
> ExportScript.Config.DAC = {}
> - first hardware
> ExportScript.Config.DAC [1] = {}
> ExportScript.Config.DAC [1] .Host = "127.0.0.1" - IP for hardware 1
> ExportScript.Config.DAC [1] .SendPort = 26026 - Port for hardware 1
> ExportScript.Config.DAC [1] .Separator = ":"
> - secound to n hardware
> --ExportScript.Config.DAC [2] = {}
> --ExportScript.Config.DAC [2] .Host = "127.0.0.1" - IP for hardware 2
> --ExportScript.Config.DAC [2] .SendPort = 9092 - Port for hardware 2
> --ExportScript.Config.DAC [2] .Separator = ":"
> 
> - Ikarus and D.A.C. can data send
> ExportScript.Config.Listener = true - false for not use
> ExportScript.Config.ListenerPort = 26027 - Listener Port for D.A.C.
> 
> - Other
> ExportScript.Config.ExportInterval = 0.05 - export evry 0.05 secounds
> ExportScript.Config.ExportLowTickInterval = 0.5 - export evry 0.5 secounds
> ExportScript.Config.LogPath = lfs.writedir () .. [[Logs \ Export.log]]
> ExportScript.Config.ExportModulePath = lfs.writedir () .. [[Scripts \ DCS-ExportScript \ ExportsModules \]]
> ExportScript.Config.Debug = false
> ExportScript.Config.SocketDebug = false
> ExportScript.Config.FirstNewDataSend = true
> ExportScript.Config.FirstNewDataSendCount = 100

TOOTLS.LUA in script \ DCS-ExportSript \ lib

> function ExportScript.Tools.FlushData ()
> local lFlushData = ExportScript.socket.protect (function ()
> if # ExportScript.SendStrings> 0 then
> local lES_SimID = ""
> 
> lES_SimID = ExportScript.SimID
> 
> local lPacket = lES_SimID .. table.concat (ExportScript.SendStrings, ExportScript.Config.IkarusSeparator) .. "\ n"
> --ExportScript.socket.try (ExportScript.UDPsender: sendto (lPacket, ExportScript.Config.IkarusHost, ExportScript.Config.IkarusPort))
> local try = ExportScript.socket.newtry (function () ExportScript.UDPsender: close () ExportScript.Tools.createUDPSender () ExportScript.Tools.ResetChangeValues ​​() end)
> try (ExportScript.UDPsender: sendto (lPacket, ExportScript.Config.IkarusHost, ExportScript.Config.IkarusPort))
> 
>         - V64 Note: Added section for DCS Interface ------------
>         if ExportScript.Config.StreamdeckExport then
>         try (ExportScript.UDPsender: sendto (lPacket, ExportScript.Config.StreamdeckHost, ExportScript.Config.StreamdeckPort))
>         end
>         - V64 Note: End of Added Section -----------------------
> 
> if ExportScript.Config.SocketDebug then
> ExportScript.Tools.WriteToLog ("FlushData: send to host:" ..ExportScript.Config.IkarusHost .. ", Port:" ..ExportScript.Config.IkarusPort .. ", Data:" ..lPacket)
> end
> 
> ExportScript.SendStrings = {}
> ExportScript.PacketSize = 0
> else
> if ExportScript.Config.SocketDebug then
> ExportScript.Tools.WriteToLog ("FlushData: nothing sent")
> end
> end
> end)
> 
> local ln, lerror = lFlushData ()
> if lerror ~ = nil then
> ExportScript.Tools.WriteToLog ("FlushData protect:" ..ExportScript.Tools.dump (ln) .. "," ..ExportScript.Tools.dump (lerror))
> end
> end

As for DCS-Bios, on the other hand, I have not made any changes, also because he sees both installations correctly and gives me green and connected them exactly the same way whether I launch the Stable or the OpenBeta.

Speaking of the logs, if I look inside DCS.LOG I don't find any error relative DCS-Bios in the OpenBeta one, indeed, the files of both instalation are very similar as regards DCS-Bios, while the DBS-BIOS.LOG in both installations it's empty if I enable de debug as suggested from you and filled with many row of limit error if debug is disabled.
Furthermore, if I disable debugging in the DCS-Bios Dashboard, I see both the Virtual Cockpit and the Console active, if instead I enable debugging, the Virtual Cockpit becomes disabled, both for Stable and for OpenBeta.
[DCS-Bios Printscreen.zip](https://github.com/charlestytler/streamdeck-dcs-interface/files/5794858/DCS-Bios.Printscreen.zip)


Finally, regarding the EXPORT.LUA file I only have the DCS-Bios related scripts, so I would exclude that other fails could create the problem.

I attach the backup of the files and folders related to the logs and the Pluging of both installations if you can and want to check.
Obviously the two installations have two separate folders and two different savedgames, and I inserted the same files in both and made the same changes.
The courses are:
[DCS-Bios file.zip](https://github.com/charlestytler/streamdeck-dcs-interface/files/5794889/DCS-Bios.file.zip)
Stable
E: \ ___ Games \ __ DCS World
C: \ Users \ sbriz \ Saved Games \ DCS
OpenBeta
C: \ Users \ sbriz \ Saved Games \ DCS.openbeta
E: \ ___ Games \ __ DCS World OpenBeta

Greetings and Thanks a lot,
Simone

**Comment by charlestytler** [comment]
The Streamdeck plugin does not use DCS-BIOS, are you using that for other purposes? Otherwise it doesn’t need to be installed. 

The DCS-ExportScript will need to be connected to your Export.lua. Can you share the contents of your Export.lua? It should contain:
‘dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]]))’

There should be a ‘Export.log’ in the logs folder when that is running.

**Comment by Valium64** [comment]
Below my entire Export.lua:

> -- load the DCS ExportScript for DAC and Ikarus
> dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]])
> 
> 
> --BIOS = {}; BIOS.LuaScriptDir = [[C:\Program Files\DCS-BIOS\dcs-lua\]]; BIOS.PluginDir = [[C:\Users\sbriz\AppData\Roaming/DCS-BIOS/Plugins\]]; if lfs.attributes(BIOS.LuaScriptDir..[[BIOS.lua]]) ~= nil then dofile(BIOS.LuaScriptDir..[[BIOS.lua]]) end --[[DCS-BIOS Automatic Setup]]

In any case at the moment I have uninstalled it and commented out its call script so that I only have the DCS-ExportScript one, but the problem remains exactly the same.
Atached of ExportScript file of the two differente installation organised as savedgame subfolder distribution if you want to check.

About Export.Log as you cha see on the zip fot Standar installation that is the one working with DCS-ExportScript I got the file, on OpenBeta folder that is giving me problem with DCS-ExportScript the isn't log file.

**Comment by Valium64** [comment]
Sorry man, I'm a rotten pumpkin head ... despite coding I forgot an "s" in my pocket when generating the OpenBeta Scripts folder, it didn't work because I called it Script without finel s, I realized it now, corrected and everything works.

Sorry again for the time I made you unnecessarily waste and thanks for the support!

**Comment by charlestytler** [comment]
No problem, glad it all worked out!

I’ve made a similar mistake in the past, adding an s accidentally to the end of DCS-ExportScript.

**Comment by Valium64** [comment]
May I just ask you one more info, not relative this question but my main DCS module? 
Since it's not an ExportModules profile for the F-14, are you working on an official profile or do you plan to work on it?
I saw on the net that there is someone working on beta which unfortunately are incomplete.

In case you do not have the module but you want to put your hand in it and you need some files let me know and I would be happy to provide you with what you need and be your tester too!

**Comment by charlestytler** [comment]
Thanks for the offer. I started this project using DCS-ExportScript since it seemed to be the most well-supported at the time with export scripts for a majority of modules. (It was also a simple implementation compared to others). And by doing so I could avoid maintenance of per-module specifics which I don't really have time for.

Unfortunately it seems to have stalled. The developer had an updated infrastructure in the works when I first spoke to him, but I'm unsure what happened. So at the moment I don't have bandwidth to take that on (or really all the questions that come with it). I may look at trying to enable Helios or DCS-BIOS compatibility as an alternative if ExportScript won't be updated.
