### ISSUE TITLE
Game crashes when F-16 TGP is selected on MFD

### ISSUE THREAD

**Issue by Nesrari** [charlestytler/streamdeck-dcs-interface#27]
DCS crashes when using DCS-ExportScripts.

https://forums.eagle.ru/topic/260024-game-crashes-when-f-16-tgp-is-selected-on-mfd/?tab=comments#comment-4551491

**Comment by charlestytler** [comment]
This was an outdated .lua file for DCS-ExportScripts, looks to have been resolved here:
https://forums.eagle.ru/topic/252202-missing-crash-logs-f-16cs-tgp-causes-the-game-to-crash/?do=getNewComment
