### ISSUE TITLE
Install/Config DCS Interface with Stream Deck

### ISSUE THREAD

**Issue by dmjohnsnx2** [charlestytler/streamdeck-dcs-interface#29]
I first want to thank you for all the work you've done on this project.

I followed your video step by step and thought I had it worked out but ran into a couple bugs. I followed the debugging instructions  on the YouTube video, the port and IP address are correct, I'm getting the log files, I got the Stream Deck export script, at least a file. It doesn't say what kind. But I can't get your export with this link to show up anything  "com.ctytler.dcs#.log

@ 2:06 in your Installation YouTube video you show an Export.lua file where you copy another Export.lua file into, I don't have that file. Is that the reason my deck is not hooking up?

One file starts out with local Tacviewlfs=require('lfs')     I'm assuming that is code, I'm not a coder so I get lost on that. Everything Else seems to work, just no 2 way comms.

**Comment by charlestytler** [comment]
Apologies, I should have specified that if that `Saved Games\Scripts\Export.lua` file doesn't exist you will need to create it.

If there is no `Scripts` folder in `Saved Games\DCS` then create that, and you can just copy the whole `Export.lua` file from DCS-ExportScript into that folder.

**Comment by dmjohnsnx2** [comment]
2 way communications
I fly the A-10C and P-51 only at this time.
Not sure where the issues are, but this is what's happening. When I push the button on the stream deck the image on the button flickers to the second state but that's it, it changes nothing in the plane. If I flip the switch in the plane, it will change the switch on the stream deck. I have watched the videos on YouTube and it seems like I have been doing exactly what you are doing in the video, a difference I see on my system is that I am running 2 monitors, sometimes if I have the stream deck open on the second monitor it will hang up and I will have to close the program and restart it. But that sounds so trivial.

**Comment by charlestytler** [comment]
You'll likely need to make sure your commands for "send value for 1st to 2nd state" and "send value for 2nd to 1st state" are correct. Since the commands are directly commanding one value (e.g. "switch up") as opposed to toggling the value, you might be in a situation where you are in the up position but the command you are sending on press is "switch up" so you never transition to the switch down state. Maybe try swapping the values in those fields to see if it works then.

**Comment by dmjohnsnx2** [comment]
Even using profiles set up by others that are within this github group, it's the same. I can not control the plane with the stream deck, but the stream deck registers what the plane is doing, or what has been done within the plane.

**Comment by charlestytler** [comment]
Closing issue due to age, reopen if there are still problems.
