### ISSUE TITLE
How to export the remaining amount of CH and FL of CMSC in F16 

### ISSUE THREAD

**Issue by HappyVoo** [charlestytler/streamdeck-dcs-interface#30]
How to export the remaining amount of CH and FL of CMSC in F16 
Cannot export 370.372.376.379

**Comment by soerenmeier** [comment]
Hi @HappyVoo either replace your `F-16C_50.lua` file with this [one](https://github.com/soerenmeier/DCS-ExportScripts/blob/f-16/Scripts/DCS-ExportScript/ExportsModules/F-16C_50.lua) or apply the [patch](https://github.com/soerenmeier/DCS-ExportScripts/commit/d283b25f319a575a16cb4c29c15a6ac9e95d5d06) to your file. Then you can use the values with the following DCS ids:
Chaff: 2000
Flares: 2001

**Comment by charlestytler** [comment]
Thanks @soerenmeier!
