### ISSUE TITLE
Streamdeck crash when trying to edit plugin button

### ISSUE THREAD

**Issue by charlestytler** [charlestytler/streamdeck-dcs-interface#31]
[Reported on DCS Forums:](https://forums.eagle.ru/topic/230609-new-streamdeck-plugin/?do=findComment&comment=4651804)

I have been using this plugin for awhile and it has been great.

Today I went to  edit an existing button, and the Stream deck crashed. OK crap happens.
After trying the same edit again, it crashed again.

Long story short. Any time I even click on an existing DCS plugin button (on the Stream deck config interface), It will crash.

If I try to add a new DCS plugin button--crash
I have tried to create new profiles, and then add a DCS button, still crash

I can edit/add any button NOT associated with DCS plugin, Stream Deck hotkey, multi action and so on with no problem.

Now what has me scratching my head is, all the buttons that I configured, back whenever ,work just fine. For example displaying fuel quantity, radio freq and so on. The buttons that are configured to change something work fine. I just can't edit or even move them.

I have un-installed/installed the DCS plugin with no change.
I have tried to create new profiles and then add a DCS button, still crash

The Stream Deck log shows  --Loading com.ctytler.dcs.sdPlugin... so it seems to load ok.

Since I did do the un-install/install, I needed to set the path to the DCS World Install Directory, but I could not do that because I can't touch a DCS button.

But I was able to set the path by editing the ..\Plugins\com.ctytler.dcs.sdPlugin\propertyinspector\js\settings_functions.js and that seems to work.

 

Anyone have any other things I could check? I have run out of things to try. 

DCS Openbeta 2.7.0.5118

Stream Deck XL x2
Stream Deck Software version 4.9.4.13228
Stream Deck Firmware version 1.00.008
Stream Deck  DCS interface 1.0.3

**Comment by tommyh454** [comment]
.\AppData\Roaming\Elgato\StreamDeck\logs
There is no log for the plugin.

[StreamDeck0.log](https://github.com/charlestytler/streamdeck-dcs-interface/files/6423726/StreamDeck0.log)
This is the StreamDeck log, I add the Windows event at the bottom of the file. 

The "onKeyPressed", at the bottom, is me changing Radio Freq and a couple of other things and are working fine.

**Comment by charlestytler** [comment]
Thanks for uploading, the plugin only publishes to the log for things like socket connection or bad path issues, so I wouldn't necessarily expect a log to be present.

As for the StreamDeck log nothing looks unusual in there to me.

There's two parts to the plugin, the C++ compiled part which runs as `..\Plugins\com.ctytler.dcs.sdPlugin\bin\dcs_interface.exe` and handles the socket communications with the lua exports, and the javascript part that runs the html/scripts in `..\Plugins\com.ctytler.dcs.sdPlugin\propertyinspector\*` for the button editing.

Since the Windows event states `Application Path: E:\Elgato\StreamDeck\StreamDeck.exe` stopped responding I think that's a good sign that hopefully the `dcs_interface.exe` isn't the part that crashed.

Some ideas of things to try: perhaps try disabling all of the javascript from running by renaming or removing the folder `..\Plugins\com.ctytler.dcs.sdPlugin\propertyinspector` temporarily. This should allow you to still see existing buttons and create new ones, but when you click on them there will be no settings other than Title to change.

If you recently upgraded the Streamdeck version, you could also try roll back to a previous version [like 4.8.2 found here](https://help.elgato.com/hc/en-us/articles/360028242631-Elgato-Stream-Deck-Software-Release-Notes).

Are you able to install other Streamdeck plugins that work?

**Comment by tommyh454** [comment]
Thank you for taking the time to look at this. 

After some more testing I don't believe it is your plugin causing the problem. I'm going to push this to Elgato/Corsair 

I did try to install another plugin and I had the same thing happen (CPU usage) but only in a  certain circumstance. I'll explain :)

I have 2 monitors and 2 XL's

Normally, when I would open StreamDeck, it would open on the secondary monitor, DCS World on the primary monitor, and I never really gave that a second thought. That is what seems to be causing the problems.

I have found that I must make sure StreamDeck is on the primary monitor, cycle through the 2 XL interfaces, then I can select one of your buttons and move/edit/configure and so on. (I was also able to add the CPU usage plugin).

So the short version, StreamDeck on Primary monitor all is good. StreamDeck on secondary monitor, no friggin good.  I have been able to reproduce this about a 100 times.

Thanks again for taking a look and for the DCS plugin.

**Comment by charlestytler** [comment]
Interesting, I actually saw someone report a similar issue while looking into this from a year ago: https://www.reddit.com/r/ElgatoGaming/comments/f6z5tq/stream_deck_crashes_whenever_i_try_to_add/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

FWIW, I have used my stream deck on a second monitor without issue so it's not always present. Thanks for responding, I'll close out this ticket here now.

**Comment by tommyh454** [comment]
Yep those folks and I have the same problem. Oh well, I have a work around and everything is fine.
Since it's been going on for over a year now, I'm sure in two weeks Elgato will get it fixed.
Thanks again.
