### ISSUE TITLE
DCS world stream deck JF-17 issue

### ISSUE THREAD

**Issue by jonny415** [charlestytler/streamdeck-dcs-interface#32]
I am trying to make rotery nob for INS Mode Knob Selector, Device ID: INS18, Button ID: 3410, DCS ID: 908. The click value not matching the JF-17 lua file. How to make it work.

**Comment by charlestytler** [comment]
This is an old ticket, if you would still like to get feedback on this I'd suggest posting in this thread to the community:
https://forums.eagle.ru/topic/230609-new-streamdeck-plugin/
