### ISSUE TITLE
Exporting F-16 Chaff and Flare Quantity

### ISSUE THREAD

**Issue by bones1014** [charlestytler/streamdeck-dcs-interface#33]
I tried following your videos and I can get the DCS-BIOS to display chaff and flare quantity correctly but when I move to the LUA file I can't get it to work. This is what I end up entering in the LUA:

		--chaff and flare quantity export
	local chaff1 = ExportScript.Tools.split(list_indication(16), "%c")[3]
	local flare1 = ExportScript.Tools.split(list_indication(16), "%c")[6]
	if chaff1 == nil then
		chaff1 = ""
	end	
	if flare1 == nil then
		flare1 = ""
	end
	
	ExportScript.Tools.SendData(6000, string.format("%-3s", chaff1))
	ExportScript.Tools.SendData(6001, string.format("%-3s", flare1))

The export script I'm using is from the DCS user files
https://www.digitalcombatsimulator.com/en/files/3312764/

What needs to be changed?

**Comment by charlestytler** [comment]
Hi please see #30 there was a fix for the lua file there.

**Comment by bones1014** [comment]
Thanks! Could you tell if I was on the right track?
