### ISSUE TITLE
Unable to Enumerate the clickable data for the Mi-24

### ISSUE THREAD

**Issue by Mr-7** [charlestytler/streamdeck-dcs-interface#35]
Unable to view clickable data from the new Mi-24 module. I've created an export module for it to just do the autopilot but i cant get the streamdeck plugin ID lookup to display anything. Mi-24 is listed as a module but the window lists no data, i notice the clickable data is seperate from the clickable defs but not sure if this is linked to the issue.

(all other modules work fine)

![image](https://user-images.githubusercontent.com/6165617/122612577-47daab80-d07b-11eb-9530-34375343a0ef.png)

**Comment by asherao** [comment]
I am seeing the same thing. Also happens with the MiG-21Bis for me.

**Comment by Mr-7** [comment]
> I am seeing the same thing. Also happens with the MiG-21Bis and A10C_2.

I’ve got around it by using the clickable data extract tool on this GitHub to pull the relevant info and manually doing it in the streamdeck plugin / making a custom export lua. Slow going but have the ATGM and auto pilot all working on the hind.

**Comment by charlestytler** [comment]
Thanks for the update that the clickable data extract tool works. The lua script in that should be the same as what's embedded in the Streamdeck plugin. 
I also can verify the plugin doesn't populate IDs for the Mi-24, I will look into what may be the issue.

**Comment by charlestytler** [comment]
This has been resolved, and the fix is available in a new release is available to install:
https://github.com/charlestytler/streamdeck-dcs-interface/releases/tag/v1.0.4
