### ISSUE TITLE
ID Lookup - information not loading for any module

### ISSUE THREAD

**Issue by CalypteCreative** [charlestytler/streamdeck-dcs-interface#47]
Hi,

I'm trying to read clickable elements in modules but data is not loading for any of the modules I have. At the same time module list loads correctly - I can see all the modules I have on a select list.

Running the newest release (1.0.4)

![DCS Interface](https://user-images.githubusercontent.com/4442429/130952939-bcbd00f9-7c0a-4bd1-aa05-a2b1eefa94d0.png)

**Comment by charlestytler** [comment]
Hi @CalypteCreative I've updated the error information in a newer build of the plugin. Could you install the newest (non-released) version downloaded from here:
https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Release/com.ctytler.dcs.streamDeckPlugin

Then after trying to select a module, within Windows Explorer you can go to `%APPDATA%\Elgato\StreamDeck\logs` and open the latest `com.ctytler.dcs#.log` file. Could you report the error message you see here?

**Comment by CalypteCreative** [comment]
Hi,

Thanks for your response. 

It seems to be a case of a repeated path. "Y:\DCSY:\DCS". Y:\DCS is my main installation folder.

01:00:37.009 F14 Clickabledata Result: Lua script runtime error (2): cannot open Y:\DCSY:\DCS\Mods\aircraft\F14\Cockpit\command_defs.lua: Invalid argument

01:01:42.816 L-39C Clickabledata Result: Lua script runtime error (2): cannot open Y:\DCSY:\DCS\Mods\aircraft\L-39C\Cockpit\devices.lua: Invalid argument

01:01:44.456 MiG-15bis Clickabledata Result: Lua script runtime error (2): cannot open Y:\DCSY:\DCS\Mods\aircraft\MiG-15bis\Cockpit\Scripts\command_defs.lua: Invalid argument

01:01:46.531 Su-33 Clickabledata Result: Lua script runtime error (2): bin/extract_clickabledata.lua:164: Could not find clickabledata.lua from Y:\DCS\Mods\aircraft\Su-33\Cockpit\ or Y:\DCS\Mods\aircraft\Su-33\Cockpit\Scripts\ (or file found but contains syntax errors)

**Comment by charlestytler** [comment]
I see, there was an assumption I had that install paths would always have "DCS" and "World" in them. I've landed a fix #49 for this, if you can try re-downloading and installing from the updated version here:
https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Release/com.ctytler.dcs.streamDeckPlugin
Let me know if that resolves your issue.

**Comment by CalypteCreative** [comment]
Still doesn't work (same wrong path as before), but your comment helped me work it out at my end - I created a mklink /j directory "DCS World" just next to the real directory :) Thanks.

If you need me to test any future releases - I will gladly check if they accept "Y:\DCS".

**Comment by charlestytler** [comment]
Hmm, I thought that should be a quick fix. I made a mock DCS folder at `D:\DCS` on my local machine and that works fine. Could you check if you accidentally installed a cached version of the download? (Note that you have to uninstall from Streamdeck before deleting the old `com.ctytler.dcs.streamDeckPlugin` file).
Thanks for uploading the logs though!

**Comment by CalypteCreative** [comment]
You're absolutely right - I got the cached version. With a proper reinstall, it works fine on Y:\DCS. Thanks! :)

**Comment by charlestytler** [comment]
Nice, thanks for testing it out
