### ISSUE TITLE
Feature suggestion - remember last IF Lookup Search

### ISSUE THREAD

**Issue by CalypteCreative** [charlestytler/streamdeck-dcs-interface#51]
Hi,

Being halfway through the F-16 cockpit I would like to share an idea for a feature. 

Would it be possible to cache the last search in ID Lookup window? That would make work much faster if the "UHF" (example) was kept in search window as it is often the case that multiple similar IDs are being looked up.

Thanks to a great tool :)

**Comment by charlestytler** [comment]
@CalypteCreative thanks for the suggestion. I haven't published a full release, but I've added this feature to master and you can download and install it from:
https://github.com/charlestytler/streamdeck-dcs-interface/blob/master/Release/com.ctytler.dcs.streamDeckPlugin
