### ISSUE TITLE
Updating DCS Interface in new version of Stream Deck software

### ISSUE THREAD

**Issue by ivaarsen** [charlestytler/streamdeck-dcs-interface#53]
Since the new version of Stream Deck software, the More Actions button has been removed in favor of a store front type interface.  I am unable to view or manage DCS Interface plugin at this time.  Documented upgrade / management instructions are out of date.  Do you have an alternate way to manage the plugin?

**Comment by charlestytler** [comment]
Have provided updated instructions in the Github Readme.
