### ISSUE TITLE
Dcs interface stopped working because of me.

### ISSUE THREAD

**Issue by gordonkatt** [charlestytler/streamdeck-dcs-interface#54]
So i was being really stupid today and just wanted to see if i could solve a teeny tiny issue i was having with simshaker at the moment and decided to press ok on the option that you see in the picture: 
![C2ACB00E-CCAC-433A-9440-A66577731490](https://user-images.githubusercontent.com/90673685/133201849-219afaa1-c3b7-4569-8387-56cee376ff67.jpeg)

So after realising something had broke i ran through the troubleshoot guide you made on another issue back in October 2020 and still nothing has worked unfortunately. So what is left to do ?

**Comment by gordonkatt** [comment]
so small update. deleted that bak file so now the buttons, switches lights etc etc are displaying the state they are in when i press the corresponding switch in the cockpit. And dcs coms has detected the modules. BUT. For some reason when i press the button on the stream deck nothing is changed in the cockpit. It is reading the state but not allowing me to send inputs.

**Comment by charlestytler** [comment]
Check the instructions under "Initial Configuration" on the GitHub readme where it asks to set the port to 1725.
There are separate send and receive ports so it may be that you receive is connected properly but send is not. 
Also check in the DCS Comms window what port is set there for Sending and that it matches the instructions and ExportScript config's ListenerPort.

**Comment by gordonkatt** [comment]
Seems to be working now, Several different lines in the config lua said both 26 and 27 at the end but it seemed to be happy at 26. Will update if it breaks again 😄

**Comment by charlestytler** [comment]
The Winwing SimAppPro exports don't play well with other export scripts. Suggest trying to reorder the includes in Export.lua if you have issues, selectively enabling/disabling them one at a time to identify which ones casuse the issue, then choose which ones you prefer if some conflict.
I don't have any influence on export scripts within this project, so outside of the scope of this plugin.
