### ISSUE TITLE
Having an issue with communication through export

### ISSUE THREAD

**Issue by sh4d0w0fd347h** [charlestytler/streamdeck-dcs-interface#55]
so backstory here, I had this working for about a month, and then something happened to dcs itself and it started crashing every time I tried to play. so I did a complete wipe and reinstall. dcs works now, but no matter what I do I cannot get the interface to work. it works on my stream deck, but when i go to DCS comms page and try to see the date I get the "module not running" message. nothing I've done has helped, I've follow the instructions to the letter, all of my settings match up. but it will not communicate between the game and the stream deck plugin. any recommendations?

**Comment by charlestytler** [comment]
It sounds like there may be an issue with the ExportScripts themselves.
See if the log files:
`...\Saved Games\DCS\Logs\Export.log`
`...\Saved Games\DCS\Logs\dcs.log`
Contain helpful information.

The wiki for the ExportScripts is here: https://github.com/s-d-a/DCS-ExportScripts/wiki/Documentation-in-English
