### ISSUE TITLE
Hotkey button with Image change

### ISSUE THREAD

**Issue by starso** [charlestytler/streamdeck-dcs-interface#57]
There is lack of momentary button with image state change but sending keystrokes instead of DCS commands. Image change should represent state of DCS values but pressing button would be ordinary hotkey.

Good example are all the toggles - one button toggles some action and button image can represent state / effect of this toggle (ew. gear up/down toggle with button representing if gear is up or down).

Hotkey should capture keystroke combination. Also differ left/right alt keys etc like Super Macro plugin for Stream Deck

**Comment by charlestytler** [comment]
I would like to keep this plugin restricted to interfacing with only Lua input/export, adding Windows keyboard key emulation would more complexity then I would like.
The Lua exports backend can be quite powerful and should be able to control all aircraft states with some work. For independent input and image state change you can use the "Momentary Button with Lamp" button type. This would allow a single button press and the image responding to something else.
For gear up/down you can use the Switch Input where you can command separate Gear Up or Gear Down commands based on if the gear is currently up or down in the game.
