### ISSUE TITLE
Using mod aircraft with the export script

### ISSUE THREAD

**Issue by bones1014** [charlestytler/streamdeck-dcs-interface#58]
I'm trying to setup an export script for the A-4E-C community mod. I appears that DCS isn't exporting controls from the Saved Games mod folder for custom aircraft. Is there a way around this?

**Comment by charlestytler** [comment]
Are you asking about ID Lookup page alone? That may work if you specify the DCS Install path as the Saved Games folder, such that it can find a `Mods/A-4E-C/...` folder at the location.

If DCS-ExportScripts isn't exporting data for the mods then you'll have to look at the lua code and log files for it to see what's the issue. Log files are located here:
- Look at Saved Games\DCS\Logs\dcs.log for any messages that may indicate an error within Lua scripts
- Look at Saved Games\DCS\Logs\Export.log for any error messages that DCS-ExportScript may output.
- (Note you can also set ExportScript.Config.Debug to true in Saved Games\DCS\Scripts\DCS-ExportScript for more detailed logging)

I am working on supporting DCS-BIOS backend in #41 that should provide better support for Mods aircraft. Until then no work planned on updating DCS-ExportScripts functionality.
