### ISSUE TITLE
Add Rotaries to Multiaction and Multiaction Switches

### ISSUE THREAD

**Issue by ozdeadmeat** [charlestytler/streamdeck-dcs-interface#59]
Can we please get the option to set Incremental Input (rotaries), and switches to the Multiaction functionality?
 I want to be able to set things like a Fence In button to turn all my aircraft external lights off etc. I also want to be able to set an NVG mode of the internal lights of my aircraft with a button.

**Comment by charlestytler** [comment]
You should be able to use the Momentary Button within Multi Action to do the things you want -- set multiple rotaries to a predefined value. The incremental input is only necessary if you want to send a different value to the rotary on each press (meaning it will store internally the last value sent and increment up on each press).

If you have an increment that is commanding values between 0.0 and 0.4 for example, and you want a multi-action to get it to the 3rd state, then use the Momentary to send 0.2 to that DCS ID.

Will that work, or are there cases where you do want multiple rotaries incremented with one button press? I could see a use for a Brightness Up multi-action that increases brightness of three MFDs at once.

**Comment by ericandi** [comment]
Thanks. I’ll give what you suggested a shot. The controls that I had set up as hot keys matching DCS keyboard shortcuts were mostly things simulator applications controls, not aircraft controls that involve interacting with a physical button, switch, or dial in the cockpit. I programmed hot keys for all of the external views, to add/remove pilot, to add/remove flight stick, and for all of the pilot communication shortcuts like calling the ball, saluting, etc.

At first I thought that it might be the left and right keyboard modifiers that was causing the issues, so then I changed all of my hot keys to single character key binds and then changed the keyboard shortcuts in DCS Control Settings to match the single character hot keys that I programmed in the SD app, but still none of the hot key stream deck buttons worked in DCS.

But if I open up a Word document and press any of the hot key buttons on my Stream Deck, the appropriate characters get typed into Word.  The hot keys also work in other flight sim apps like MSFS2020.

I read something on a forum this morning where some other people said they ran into the same issue as me whenever they had the stream deck application open with the stream deck window on a secondary monitor, while DCS is displayed on their main monitor.

I had the stream deck app opened on a secondary monitor with DCS on my main monitor, but I also tried to use my streams deck hot keys with the stream deck application closed altogether and the hot keys still didn’t work.

I will try keeping the stream deck app opened oj my main monitor, but if that doesn’t work, will the momentary buttons work for control simulator functions that don’t have a corresponding physical button, switch, dial, stick, pedal, or throttle in the aircraft?


Best Regards,
Eric Reyes
407-310-0096
***@***.*** <https://aka.ms/o0ukef>
________________________________

**Comment by charlestytler** [comment]
Will close this as I think there is a solution in today's version that can accommodate  the need. Re-open and specify if it does not.

**Comment by ozdeadmeat** [comment]
Is there any instructions on how I can do this with the new update?

**Comment by ozdeadmeat** [comment]
There is still no way to add incrimental actions to a multi-action switch.
