### ISSUE TITLE
Question about lever

### ISSUE THREAD

**Issue by gordonkatt** [charlestytler/streamdeck-dcs-interface#60]
So i hope this is okay to ask a question here. Alot of the buttons which are recommended to be binded to an LEV are these possible to bind to an physical rotary or sliding axis on a buttonbox/throttle ? Reason i ask is becuase for some modules that have alot of in game rotaries are sometimes unable to be binded to a rotary or slider axis only encoders in the controller setup so I thought this was a way of circumventing this :)

**Comment by charlestytler** [comment]
Sure, I would think most of the "LEV" type controls would have axis bindings in the control settings. If there is not, it's likely possible to add an axis binding to DCS itself so you can assign it in the DCS Controls options.

Is there an example you have? I can try help.

**Comment by charlestytler** [comment]
For details on modifying in-game keybind options see an example here:
https://www.reddit.com/r/hoggit/comments/7wli5i/how_to_add_extra_bindings_for_clickable_cockpit/

And a more detailed guide (pdf) here:
https://forums.eagle.ru/applications/core/interface/file/attachment.php?id=97570
