### ISSUE TITLE
help setting up NMSP buttons on A10C

### ISSUE THREAD

**Issue by bwanaaa** [charlestytler/streamdeck-dcs-interface#61]
Using a momentary button with lamp, I can successfully change the state of the button in DCS. As ingle press will turn on ILS, and a subsequent press will turn off ILS. However when the appropriate on-off icons are added, the lamp only displays the 'on' state while the button is pressed. This is expected behavior since the switch only sends a '1' while it is pressed.

To maintain a 'latched' state on the stream deck, I tried to configure a switch button. The appropriate icons were used and again the image state change was set appropriately. 
DCS ID: 617
'Show 2nd State Image When:' greater than or equal to 'Value' : 0
The lamp on the stream deck functions correctly. One press lights it up and another turns it off.
Then the DCS command dropdown for the switch input was configured appropriately. The specific entries were:
'Send Value for 1st -> 2nd State:' 1
'Send Value for 2nd -> 1st State:' 0

Pressing the ILS button on the NMSP while in a mission in DCS changes the state  in DCS from unlit to lit-the light on the button in DCS behaves latched ; the button behavior however is like a momentary-it pops right out when it is released.

This causes a weired behavior on the streamdeck. The streamdeck button is lit for only as long as the button is depressed in the game. The instant you release it, the streamdeck lamp goes dark.
The behavior observed bvy using the streamdeck is equally weird.
An initial press on the streamdeck causes the light on streamdeck to come on, the lamp on the ILS button also comes on but the button shows itself 'depressed' as if its position is latched as well. Another press of the stream deck button returns the the image in DCS to a 'popped out state' and its lamp remains lit. However the stream deck lamp is extinguished-the stream deck is behaving appropriately because from its point of view, its state has to change with a second button push.

In summary, weird behavior is observed because the button in DCS has two different behaviors-its illumination state behaves like a switch but its position state (depressed or popped out) behaves like a momentary.
Maybe there is a way to do this with the current functionalities but I cannot figure it out.

My solution would be to make two changes to the "Momentary Button with Lamp"

Add a checkbox and a field to the "DCS Command (on Button Press) Settings"
   "Accumulate Button Presses"   checkbox
   "Maximum Accumulated Value"   integer
    
In the the "Image State Change on DCS Update Settings" add entries to entries to the "Show 2nd State Image When:"  
The entries in the "Show 2nd State Image When:" would be:
    "is greater than (>) below value"
    "is equal to (==) below value"
    "is less than (>) below value"
     "accumulated button press count is even"
     "accumulated button press count is odd"

The "Momentary Button with Lamp" could be configured thusly"

"DCS Command (on Button Press) Settings"
    "Accumulate Button Presses"    checked
    "Maximum Value"  1

'Image State Change on DCS Update Settings' 
"Show 2nd State Image When:"   "accumulated button press count is even"

Now after you press the "ILS" button on the streamdeck, it gets lit on the streamdeck siince the accumulated value is 1, but since the live value is 0 when the streamdeck button is released, the button in DCS 'pops out'. Push the "ILS" button again on the streamdeck, the accumulated value cycles to 0, it's even again so the icon on the streamdeck goes back to the off state.

You could even make the choices in  the "Show 2nd State Image When:" more elaborate to allow different images to show as the count increases. You would also have to change the icon so that instead of showing two radio buttons (indicating the two different states of the value variable) there would be an integer field displaying 'accumulated button presses". Then you could assign a different icon to each "accumulated button presses" state.

I guess my issue is a clearer 'noob' explanation of issue #57 "Hotkey button with Image change".
My solution would also address issue #9 "Allow option for switch input independent of image state".

With the more elaborate change I suggested two paragraphs above, you could solve issue # 28 "Switch with three icons/images", issue #59 "Add Rotaries to Multiaction and Multiaction Switches", issue #60 "Question about lever"

**Comment by charlestytler** [comment]
It sounds like you may be running into the issue of using button state (instead of lamp state) for the Image State Change settings (they are independent of each other).

See this video and see if it applies to your situation: https://www.youtube.com/watch?v=eCGMhd5IgYU

**Comment by bwanaaa** [comment]
solved.Thank you.
