### ISSUE TITLE
Image States not always updating properly if not visible on Stream Deck

### ISSUE THREAD

**Issue by Faelan-Wolfheart** [charlestytler/streamdeck-dcs-interface#7]
There seems to be an issue with all elements that have a 2nd image state where they don't always reflect the state that they're supposed to be in. This typically happens when the element is not currently visible on the Stream Deck, then manipulated either in DCS or via another currently visible element.

Steps to reproduce - this example uses the Hornet battery switch:

1. Create ‘Switch Input’ element on Stream Deck.
2. Set the following attributes
    1. DCS Command
        1. Button ID: 3001
        2. Device ID: 3
        3. Send Value for 1st -> 2nd State: 1
        4. Send Value for 2nd -> 1st State: 0
	2. Image State Change on DCS Update Settings
		1. DCS ID: 404
		2. Show 2nd State Image When: is equal to (==) below value
		3. Value: 1
	3.	Title Text Change on DCS Update Settings
		1. DCS ID: 404
		2. Vertical Spacing: 0
		3. Display string unaltered: Checkmarked
3. Create a 'Stream Deck - > Create Folder' element next to the 'Switch Input' element
4. Go into the newly created folder and create a 'Switch Input' element identical to the above in step 2
5. Start a mission in the Hornet using a cold and dark cockpit start
6. 'Switch Input' element should correctly display 0 and be in the 1st image state
7. Press 'Switch Input' button on Stream Deck and observe it switching to the 2nd image state. It should also now show the value of 1 instead of 0 and the battery in the Hornet should come alive.
8. Exit folder and observe that the first 'Input Switch' next to the 'Folder' element correctly shows the 2nd image state and the value 1
9. Press on the 'Input Switch' element button on the Stream Deck and observe that the element changes to the 1st image state, changes its value to 0 and the battery in the Hornet turns off
10. Press on the 'Folder' element button on the Stream Deck to go into the folder and observe that the 'Switch Input' element in the folder correctly shows the newly update value of 0, but incorrectly shows the 2nd image state representing the switch being on (value == 1) even though it is off

This issue can also be witnessed in other cases. A common one is to start a mission with cold and dark cockpit, flip switches visibly shown on the Stream Deck that start in an off state (1st image) to on (2nd image), then navigate to a different folder on the Stream Deck, exit the mission and restart it. Upon re-entering the folder where the switches were flipped on, they still show as being on. This persists even if quitting and restarting the Stream Deck software.

**Comment by charlestytler** [comment]
@Faelan-Wolfheart thanks for the detailed reproduction steps. I was also able to see this issue for any buttons that were not visible and already in their SECOND state.

I have put up PR #8 which includes the fix. I will include this in the next release, however if you'd like to try the fix sooner you can install the plugin from that branch via `Release/com.ctytler.dcs.streamDeckPlugin`

**Comment by charlestytler** [comment]
The fix has now been released in v1.0.3
