### ISSUE TITLE
Interface not communicating in singleplayer

### ISSUE THREAD

**Issue by gordonkatt** [charlestytler/streamdeck-dcs-interface#74]
So dcs interface work great for me with any module as long as it is an multiplayer mission. But whenever I start a singleplayer mission it stops communicating for some reason. Is there any fix ? :)

**Comment by gordonkatt** [comment]
Yep now tried a range of different servers and they all work as in dcs interface communicates with the module. But whenever I try it with a mission i made in single player or pre made missions it fails. It even somehow doesnt work with my own singleplayer missions when i try to host a server and run them.

**Comment by charlestytler** [comment]
It sounds like there may be something erroring in the DCS-ExportScript .lua scripts. There's a couple things I would suggest checking/trying:

Look at Saved Games\DCS\Logs\dcs.log for any messages that may indicate an error within Lua scripts
Look at Saved Games\DCS\Logs\Export.log for any error messages that DCS-ExportScript may output.
(Note you can also set ExportScript.Config.Debug to true in Saved Games\DCS\Scripts\DCS-ExportScript for more detailed logging)

**Comment by gordonkatt** [comment]
I have checked them and it seems to listen when Im in a multiplayer mission but not a single player one. When i load in the multiplayer slot in lets take the F14 all buttons on the streamdeck works and the export log says: ======End========
17:50:55:442 : run hight importance export Ikarus. Before this end messege after spawn in I can see that it also lists all of the ids for all functions contained in the export module lua.


Once i try this in any mission I creatred in singleplayer nothing works and the log just says it has created : ExportScript Version: 1.2.1
17:53:51:240 : Create UDPSender
17:53:51:240 : Create UDPListner.     It does nothing of the above either

**Comment by gordonkatt** [comment]
It now game me this when i loaded it up in an fast action auto generated mission in Single player still not working: 
17:59:53:733 : File Path: C:\Users\oscar\Saved Games\DCS.openbeta\Scripts\DCS-ExportScript\ExportsModules\F-14B.lua
17:59:53:734 : File 'C:\Users\oscar\Saved Games\DCS.openbeta\Scripts\DCS-ExportScript\ExportsModules\F-14B.lua' loaded
17:59:53:734 : Version:
17:59:53:734 : Config: 1.2.1
17:59:53:734 : Maps: 1.2.1
17:59:53:734 : Tools: 1.2.1
17:59:53:736 : F14: 1.2.1
17:59:53:736 : genericRadio: 1.2.1
17:59:53:736 : ExportScript: 1.2.1
17:59:53:736 : ExportScript.ConfigEveryFrameArguments Count: 945
17:59:53:736 : ExportScript.ConfigArguments Count: 415
17:59:53:736 : Detected Map: CaucasusBase

**Comment by gordonkatt** [comment]
This is the export log when starting up a random singleplayer mission where dcs interface doesnt work: ExportScript Version: 1.2.1
21:37:02:483 : Create UDPSender
21:37:02:483 : Create UDPListner
21:37:02:483 : MyInfo: {
    [Pitch] = number: "0"
    [Type] = {
        [level3] = number: "1"
        [level1] = number: "1"
        [level4] = number: "265"
        [level2] = number: "1"
    }
    [Country] = number: "2"
    [GroupName] = string: "olle37"
    [Flags] = {
        [Jamming] = boolean: "false"
        [IRJamming] = boolean: "false"
        [Born] = boolean: "true"
        [Static] = boolean: "false"
        [Invisible] = boolean: "false"
        [Human] = boolean: "true"
        [AI_ON] = boolean: "true"
        [RadarActive] = boolean: "false"
    }
    [Coalition] = string: "Enemies"
    [Heading] = number: "2.4360673427582"
    [Name] = string: "AJS37"
    [Position] = {
        [y] = number: "15.339942932129"
        [x] = number: "-281191.65625"
        [z] = number: "646855.25"
    }
    [UnitName] = string: "Gungnir"
    [LatLongAlt] = {
        [Long] = number: "42.04369329962"
        [Lat] = number: "42.246507519242"
        [Alt] = number: "15.339942932129"
    }
    [CoalitionID] = number: "2"
    [Bank] = number: "0"
}

21:37:02:485 : File Path: C:\Users\oscar\Saved Games\DCS.openbeta\Scripts\DCS-ExportScript\ExportsModules\AJS37.lua
21:37:02:485 : File 'C:\Users\oscar\Saved Games\DCS.openbeta\Scripts\DCS-ExportScript\ExportsModules\AJS37.lua' loaded
21:37:02:485 : Version:
21:37:02:485 : Config: 1.2.1
21:37:02:485 : Maps: 1.2.1
21:37:02:485 : Tools: 1.2.1
21:37:02:485 : AJS37: 1.2.1
21:37:02:485 : genericRadio: 1.2.1
21:37:02:485 : ExportScript: 1.2.1
21:37:02:485 : ExportScript.ConfigEveryFrameArguments Count: 115
21:37:02:485 : ExportScript.ConfigArguments Count: 152
21:37:02:485 : Detected Map: CaucasusBase




This is a few minutes later the same export script log when I instead spawn in a multiplayer mission where the interface WORKS everytime:

ExportScript Version: 1.2.1
21:45:55:023 : Create UDPSender
21:45:55:023 : Create UDPListner
21:45:59:408 : No Module Found.
 21:46:54:389 : run hight importance export Ikarus
21:46:54:404 : run hight importance export universally
21:46:54:404 : ======Begin========
21:46:54:404 : 1. ID: 121, Fromat: %.4f, Value: 0.0192
21:46:54:404 : 2. ID: 122, Fromat: %.4f, Value: 0.0000
21:46:54:404 : 3. ID: 124, Fromat: %.4f, Value: 0.1109
21:46:54:404 : 4. ID: 125, Fromat: %.4f, Value: 0.0111
21:46:54:404 : 5. ID: 127, Fromat: %.4f, Value: 0.1180
21:46:54:404 : 6. ID: 128, Fromat: %.4f, Value: 0.9156
21:46:54:404 : 7. ID: 130, Fromat: %.4f, Value: 0.0830


And this is what really confuses me about the error as this is caused for all modules. It somehows does the necessary steps to work in a multiplayer mission but why doesnt it do the same when I use the module in Single player mission :/ ?

**Comment by gordonkatt** [comment]
So any idea what might be causing dcs interface/bios to only work when im using a module on the dedicated servers but not working on missions which are hosted or in singleplayer ? 🤷‍♂️😕

**Comment by gordonkatt** [comment]
So i have now completely reinstalled dcs and done repair and clean up. I also completely redid the dcs export script installation and reinstalled your plugin and remade and reordered the export script lua trying to put the dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]] in different orders and I also tried following the export script lua line order that my friend who also uses dcs interface have as his dcs interface works with singleplayer missions. 

I am at a bit of a loss here judging by me going over everything of interest but interface will for me for some reason not work in singleplayer or hosted missions it only creates the neccesery steps and communicates in dedicated servers :/
